project:
  type: website

website:
  title: "Casual Inference"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Resources"
        href: resources/index.qmd
      - text: "About"
        href: about/index.qmd
    right:
      - icon: github
        href: https://github.com/Jonathan-Pearce
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/YOUR-LINKEDIN
        target: _blank
  favicon: images/placeholder.svg

format:
  html:
    css: styles/styles.css
